# Nome do workflow que aparece no GitHub
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Lista de Jobs
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    # Passo 2: Configurar Java 21
    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Passo 3: Executar Teste
    - name: Executar Testes
      run: mvn -B test --file pom.xml